image:
  name: eu.gcr.io/savannah-emr/fls-image:09-03-21-nullsafety

stages:
  - test

core_domain_tests:
  stage: test
  timeout: 5 minutes
  tags:
    - healthcloud-multi
  script:
    - flutter pub get
    - flutter analyze
    - flutter test --coverage test
    - genhtml -q -o coverage coverage/lcov.info
    - python3 check_coverage.py 
