name: domain_objects
description: Home for all shared domain objects that are common for both bewell-consumer and bewell-professional app
version: 0.0.32-nullsafety
homepage: https://github.com/savannahghi/domain_objects
repository: https://github.com/savannahghi/domain_objects
issue_tracker: https://github.com/savannahghi/domain_objects/issues
documentation: https://github.com/savannahghi/domain_objects/tree/main/doc

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  dartz: ^0.10.0-nullsafety.2
  flutter:
    sdk: flutter
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  intl: ^0.17.0
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  test:

flutter:
