name: sil_core_domain_objects
description: Home for all shared domain objects that are common for both consumer and professional app
version: 0.0.1
author: dmwangi@savannahinformatics.com
homepage: https://gitlab.slade360emr.com/optimalhealth/dart_utils/sil_core_domain_objects


environment:  
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"
  

dependencies:
  dartz: ^0.10.0-nullsafety.2
  flutter:
    sdk: flutter  
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2 
  intl: ^0.17.0
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3  

dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  test:   


flutter:

  
